#pragma once
#include <Windows.h>

#define TAB_PAGES	6
#define TAB_COMPONENTS	150
#define TAB_TABLECOMPONENTS	11

#define START_ID_BUTTON	2000

#define TAB_PAGE_TIMER	0
#define TAB_PAGE_PIXELEVENTS	1
#define TAB_PAGE_ALARM			2

#define FIELDS_TIMER_PAGE 8 
#define FIELD_ACTIVE_TIMER_PAGE(x)				(0 + FIELDS_TIMER_PAGE * x)
#define FIELD_BUTTON_TIMER_PAGE(x)				(1 + FIELDS_TIMER_PAGE * x) 
#define FIELD_PERIOD_TIMER_PAGE(x)				(2 + FIELDS_TIMER_PAGE * x) 
#define FIELD_NUMREPEAT_TIMER_PAGE(x)			(3 + FIELDS_TIMER_PAGE * x)
#define FIELD_DELAY_TIMER_PAGE(x)				(4 + FIELDS_TIMER_PAGE * x)
#define FIELD_CTRL_TIMER_PAGE(x)				(5 + FIELDS_TIMER_PAGE * x)
#define FIELD_ALT_TIMER_PAGE(x)					(6 + FIELDS_TIMER_PAGE * x)
#define FIELD_SHIFT_TIMER_PAGE(x)				(7 + FIELDS_TIMER_PAGE * x)

#define ID_ACTIVE_TIMER_PAGE					(2000)
#define ID_BUTTON_TIMER_PAGE					(2001)
#define ID_PERIOD_TIMER_PAGE(x)					(2020 + x)
#define ID_NUMREPEAT_TIMER_PAGE(x)				(2040 + x)
#define ID_DELAY_TIMER_PAGE(x)					(2060 + x)
#define ID_SHIFT_TIMER_PAGE						(2080)
#define ID_CTRL_TIMER_PAGE						(2081)
#define ID_ALT_TIMER_PAGE						(2082)

#define FIELDS_PIXELEVENTS_PAGE 12 
#define FIELD_ACTIVE_PIXELEVENTS_PAGE(x)		(0 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_BUTTON_PIXELEVENTS_PAGE(x)		(1 + FIELDS_PIXELEVENTS_PAGE * x) 
#define FIELD_CONDITION_PIXELEVENTS_PAGE(x)		(2 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_SETCOLOR_PIXELEVENTS_PAGE(x)		(3 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_GETCOLOR_PIXELEVENTS_PAGE(x)		(4 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_BUTTONSETPIXEL_PIXELEVENTS_PAGE(x)	(5 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_POSITIONPIXEL_PIXELEVENTS_PAGE(x)	(6 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_PERIOD_PIXELEVENTS_PAGE(x)		(7 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_DELAY_PIXELEVENTS_PAGE(x)			(8 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_CTRL_PIXELEVENTS_PAGE(x)			(9 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_ALT_PIXELEVENTS_PAGE(x)			(10 + FIELDS_PIXELEVENTS_PAGE * x)
#define FIELD_SHIFT_PIXELEVENTS_PAGE(x)			(11 + FIELDS_PIXELEVENTS_PAGE * x)

#define ID_ACTIVE_PIXELEVENTS_PAGE				(2100)
#define ID_BUTTON_PIXELEVENTS_PAGE				(2101)
#define ID_CONDITION_PIXELEVENTS_PAGE			(2102)
#define ID_PERIOD_PIXELEVENTS_PAGE(x)			(2120 + x)
#define ID_BUTTONSETPIXEL_PIXELEVENTS_PAGE(x)	(2140 + x)
#define ID_DELAY_PIXELEVENTS_PAGE(x)			(2160 + x)
#define ID_CTRL_PIXELEVENTS_PAGE				(2180)
#define ID_ALT_PIXELEVENTS_PAGE					(2181)
#define ID_SHIFT_PIXELEVENTS_PAGE				(2182)

#define FIELDS_ALARM_PAGE 10 
#define FIELD_ACTIVE_ALARM_PAGE(x)				(0 + FIELDS_ALARM_PAGE * x)
#define FIELD_CONDITION_ALARM_PAGE(x)			(1 + FIELDS_ALARM_PAGE * x)
#define FIELD_SETCOLOR_ALARM_PAGE(x)			(2 + FIELDS_ALARM_PAGE * x)
#define FIELD_GETCOLOR_ALARM_PAGE(x)			(3 + FIELDS_ALARM_PAGE * x)
#define FIELD_BUTTONSETPIXEL_ALARM_PAGE(x)		(4 + FIELDS_ALARM_PAGE * x)
#define FIELD_POSITIONPIXEL_ALARM_PAGE(x)		(5 + FIELDS_ALARM_PAGE * x)
#define FIELD_BEEPFREQ_ALARM_PAGE(x)			(6 + FIELDS_ALARM_PAGE * x)
#define FIELD_BEEPPERIOD_ALARM_PAGE(x)			(7 + FIELDS_ALARM_PAGE * x)
#define FIELD_BEEPLEN_ALARM_PAGE(x)				(8 + FIELDS_ALARM_PAGE * x)
#define FIELD_SOUND_ALARM_PAGE(x)				(9 + FIELDS_ALARM_PAGE * x)

#define ID_ACTIVE_ALARM_PAGE					(2200)
#define ID_CONDITION_ALARM_PAGE					(2201)
#define ID_SOUND_ALARM_PAGE						(2202)
#define ID_BUTTONSETPIXEL_ALARM_PAGE(x)			(2210 + x)
#define ID_BEEPFREQ_ALARM_PAGE(x)				(2220 + x)
#define ID_BEEPPERIOD_ALARM_PAGE(x)				(2230 + x)
#define ID_BEEPLEN_ALARM_PAGE(x)				(2240 + x)


enum {
	OnMenuActionSave,
	OnMenuActionOpen,
	OnMenuActionPathFile,

	IDTimer,

	StartButtonClik,
	StopButtonClik,

	SearchWindowHandlesButtonClik,

	ID_COMPONENTSUSER,

	ID_LISTBOX_SearchWindowHandles,
	ClickButtonSearchWindowHandles,

	CheckBoxUSB,
	CheckBoxMarkPixel,	

	OnExitSoftware,
};

